apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatewayd.fullname" . }}
  labels:
    app: gatewayd
data:
  GATEWAYD_CLIENTS_DEFAULT_ADDRESS: {{ .Values.gatewayd.clients.default.address }}
  GATEWAYD_LOGGERS_DEFAULT_LEVEL: {{ .Values.gatewayd.loggers.default.level }}
