apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatewayd.fullname" . }}
  labels:
    {{- include "gatewayd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gatewayd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gatewayd.labels" . | nindent 8 }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gatewayd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /usr/bin
              gatewayd plugin install --skip-path-slip-verification --output-dir /usr/bin --plugin-config /etc/gatewayd_plugins.yaml --cleanup=true --overwrite-config=false --update
              gatewayd run --config /etc/gatewayd.yaml --plugin-config  /etc/gatewayd_plugins.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.extraEnvVars}}
          env:
            {{- range $key, $value := .Values.extraEnvVars }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          {{- end}}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 18080
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or (.Values.gatewaydPluginsConfig.enabled) (.Values.gatewaydConfig.enabled) }}
          volumeMounts:
          {{- if .Values.gatewaydPluginsConfig.enabled }}
          - name: plugin-config-volume
            mountPath: /etc/gatewayd_plugins.yaml
            subPath: gatewayd_plugins.yaml
          {{- end }}
          {{- if .Values.gatewaydConfig.enabled }}
          - name: gatewayd-config-volume
            mountPath: /etc/gatewayd.yaml
            subPath: gatewayd.yaml
          {{- end }}
          {{- end }}
      {{- if or (.Values.gatewaydPluginsConfig.enabled) (.Values.gatewaydConfig.enabled) }}
      volumes:
      {{- if .Values.gatewaydPluginsConfig.enabled }}
      - name: plugin-config-volume
        configMap:
          name: {{ .Release.Name }}-plugins-config
      {{- end }}
      {{- if .Values.gatewaydConfig.enabled }}
      - name: gatewayd-config-volume
        configMap:
          name: {{ .Release.Name }}-config
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
