{{- if .Values.gatewaydPluginsConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-plugins-config
data:
  gatewayd_plugins.yaml: |
{{ .Files.Get "files/gatewayd_plugins.yaml" | indent 4 }}
{{- end }}
